import { Sticker, Listing } from "./types";

export const STICKERS: Sticker[] = [
  {
    id: "stk_1",
    name: "Ney Gold",
    category: "Craques Atuais",
    rarity: "Lendária",
    emoji: "⚽",
    gradient: "from-amber-400 via-yellow-500 to-amber-600",
    description: "Coleção Brasil de Ouro. O craque com drible desconcertante e chute preciso.",
    number: "FT-011",
    releaseYear: 2026,
  },
  {
    id: "stk_2",
    name: "Messi Mágico",
    category: "Craques Atuais",
    rarity: "Lendária",
    emoji: "🔟",
    gradient: "from-sky-400 via-indigo-600 to-blue-700",
    description: "O gênio argentino que conquistou o mundo com dribles milimétricos e genialidade pura.",
    number: "FT-010",
    releaseYear: 2026,
  },
  {
    id: "stk_3",
    name: "Mbappé Flash",
    category: "Craques Atuais",
    rarity: "Rara",
    emoji: "⚡",
    gradient: "from-blue-500 via-indigo-500 to-red-500",
    description: "Velocidade explosiva e finalização fulminante. Um raio pelos lados do campo.",
    number: "FT-007",
    releaseYear: 2026,
  },
  {
    id: "stk_4",
    name: "Ronaldinho Bruxo",
    category: "Lendas do Futebol",
    rarity: "Épica",
    emoji: "🤙",
    gradient: "from-purple-600 via-pink-600 to-yellow-500",
    description: "O Rei do Joga Bonito. Elásticos, lençóis e comemorações lendárias que marcaram época.",
    number: "FT-084",
    releaseYear: 2006,
  },
  {
    id: "stk_5",
    name: "Vini Jr Ousadia",
    category: "Craques Atuais",
    rarity: "Lendária",
    emoji: "🕺",
    gradient: "from-green-400 via-yellow-400 to-blue-500",
    description: "O herói das viradas europeias. Alegria, gingado brasileiro e letalidade no mano a mano.",
    number: "FT-101",
    releaseYear: 2026,
  },
  {
    id: "stk_6",
    name: "Ronaldo Fenômeno",
    category: "Lendas do Futebol",
    rarity: "Épica",
    emoji: "🇧🇷",
    gradient: "from-emerald-500 via-yellow-400 to-emerald-700",
    description: "Ronaldo R9. Arranques indefensáveis, dribles fantásticos e poder de decisão inigualável.",
    number: "FT-009",
    releaseYear: 2002,
  },
  {
    id: "stk_7",
    name: "Haaland Cyborg",
    category: "Craques Atuais",
    rarity: "Rara",
    emoji: "🤖",
    gradient: "from-sky-300 via-blue-400 to-indigo-600",
    description: "A máquina de gols norueguesa. Força física extrema e instinto finalizador impecável.",
    number: "FT-042",
    releaseYear: 2026,
  },
  {
    id: "stk_8",
    name: "Kroos Precision",
    category: "Craques Atuais",
    rarity: "Comum",
    emoji: "🎯",
    gradient: "from-slate-300 via-slate-400 to-blue-900",
    description: "O mestre dos passes milimétricos. Visão de jogo cirúrgica que controla o meio de campo.",
    number: "FT-004",
    releaseYear: 2024,
  },
  {
    id: "stk_9",
    name: "CR7 Legend",
    category: "Craques Atuais",
    rarity: "Lendária",
    emoji: "🐐",
    gradient: "from-red-500 via-amber-500 to-yellow-500",
    description: "O robô das decisões. Treino incansável e presença de área esmagadora.",
    number: "FT-007",
    releaseYear: 2026,
  },
  {
    id: "stk_10",
    name: "Salah Pharaoh",
    category: "Craques Atuais",
    rarity: "Comum",
    emoji: "👑",
    gradient: "from-red-600 via-yellow-600 to-emerald-600",
    description: "O rei egípcio da Premier League. Habilidade refinada e cortes rápidos para a perna esquerda.",
    number: "FT-003",
    releaseYear: 2025,
  },
  {
    id: "stk_11",
    name: "KDB Maestro",
    category: "Craques Atuais",
    rarity: "Épica",
    emoji: "🎩",
    gradient: "from-cyan-400 via-sky-500 to-blue-600",
    description: "O cérebro belga capaz de achar passes onde ninguém mais consegue ver espaço.",
    number: "FT-207",
    releaseYear: 2026,
  },
  {
    id: "stk_12",
    name: "Yashin Aranha",
    category: "Goleiros & Defensores",
    rarity: "Comum",
    emoji: "🧤",
    gradient: "from-neutral-700 via-neutral-800 to-black",
    description: "O lendário Aranha Negra. O único goleiro a vencer a Bola de Ouro na história do esporte.",
    number: "FT-001",
    releaseYear: 1963,
  },
  {
    id: "stk_13",
    name: "Pelé #10",
    category: "Copa do Mundo",
    rarity: "Lendária",
    emoji: "⚽",
    gradient: "from-yellow-400 via-amber-500 to-yellow-600",
    description: "Copa 1970. O Rei do Futebol em sua maior consagração mundial com a lendária camisa 10.",
    number: "CP-010",
    releaseYear: 1970,
  },
  {
    id: "stk_14",
    name: "Neymar Jr (Gold)",
    category: "Copa do Mundo",
    rarity: "Lendária",
    emoji: "🇧🇷",
    gradient: "from-emerald-450 via-yellow-400 to-emerald-600",
    description: "Gold Prizm. Edição especial e ultra rara do craque brasileiro na Copa do Mundo.",
    number: "CP-011",
    releaseYear: 2022,
  },
  {
    id: "stk_15",
    name: "Marta #10 (Rainha)",
    category: "Copa do Mundo",
    rarity: "Épica",
    emoji: "👑",
    gradient: "from-teal-400 via-emerald-500 to-emerald-700",
    description: "Special Ed. A Rainha do futebol com classe e habilidade de Copa do Mundo.",
    number: "CP-012",
    releaseYear: 2019,
  },
  {
    id: "stk_16",
    name: "Logo Oficial Brasil",
    category: "Escudos & Logos",
    rarity: "Comum",
    emoji: "🔰",
    gradient: "from-green-500 via-yellow-300 to-blue-600",
    description: "Shiny Chrome. O escudo de cinco estrelas que impõe respeito no futebol mundial.",
    number: "CP-001",
    releaseYear: 2026,
  },
  {
    id: "stk_17",
    name: "Maradona Divine",
    category: "Copa do Mundo",
    rarity: "Lendária",
    emoji: "🇦🇷",
    gradient: "from-sky-300 via-white to-blue-500",
    description: "Copa 1986. A Mão de Deus e o gol do século imortalizados no álbum mundial.",
    number: "CP-086",
    releaseYear: 1986,
  },
  {
    id: "stk_18",
    name: "Zidane Magic",
    category: "Copa do Mundo",
    rarity: "Épica",
    emoji: "🇫🇷",
    gradient: "from-blue-600 via-white to-red-650",
    description: "Copa 1998. O gênio francês que comandou o meio-campo no título mundial.",
    number: "CP-098",
    releaseYear: 1998,
  }
];

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: "lst_1",
    stickerId: "stk_1", // Ney Gold
    sellerId: "usr_alice",
    sellerName: "Alice Trader",
    price: 350.00,
    condition: "Excelente",
    status: "Ativo",
    createdAt: "2026-06-03T10:00:00Z",
  },
  {
    id: "lst_2",
    stickerId: "stk_3", // Mbappé Flash
    sellerId: "usr_bob",
    sellerName: "Bob Cards",
    price: 90.00,
    condition: "Excelente",
    status: "Ativo",
    createdAt: "2026-06-02T14:30:00Z",
  },
  {
    id: "lst_3",
    stickerId: "stk_4", // Ronaldinho Bruxo
    sellerId: "usr_carol",
    sellerName: "Carol (CopaHunter)",
    price: 180.00,
    condition: "Muito Bom",
    status: "Ativo",
    createdAt: "2026-06-03T18:15:00Z",
  },
  {
    id: "lst_4",
    stickerId: "stk_6", // Ronaldo Fenômeno
    sellerId: "usr_david",
    sellerName: "FutCollector",
    price: 210.00,
    condition: "Excelente",
    status: "Ativo",
    createdAt: "2026-06-04T09:00:00Z",
  },
  {
    id: "lst_5",
    stickerId: "stk_8", // Kroos Precision
    sellerId: "usr_carol",
    sellerName: "Carol (CopaHunter)",
    price: 25.00,
    condition: "Marcas de Uso",
    status: "Ativo",
    createdAt: "2026-06-01T11:20:00Z",
  },
  {
    id: "lst_6",
    stickerId: "stk_11", // KDB Maestro
    sellerId: "usr_bob",
    sellerName: "Bob Cards",
    price: 160.00,
    condition: "Excelente",
    status: "Ativo",
    createdAt: "2026-06-04T12:00:00Z",
  },
  {
    id: "lst_7",
    stickerId: "stk_13", // Pelé #10
    sellerId: "usr_alice",
    sellerName: "Alice Trader",
    price: 850.00,
    condition: "Excelente",
    status: "Ativo",
    createdAt: "2026-06-04T12:10:00Z",
  },
  {
    id: "lst_8",
    stickerId: "stk_14", // Neymar Jr (Gold)
    sellerId: "usr_mariana",
    sellerName: "Mariana (StickerHunter)",
    price: 320.00,
    condition: "Excelente",
    status: "Ativo",
    createdAt: "2026-06-04T12:15:00Z",
  },
  {
    id: "lst_9",
    stickerId: "stk_15", // Marta #10 (Rainha)
    sellerId: "usr_vinicius",
    sellerName: "Vinícius Admin",
    price: 150.00,
    condition: "Excelente",
    status: "Ativo",
    createdAt: "2026-06-04T12:20:00Z",
  },
  {
    id: "lst_10",
    stickerId: "stk_16", // Logo Oficial Brasil
    sellerId: "usr_felipe",
    sellerName: "Felipe (Colecionador)",
    price: 15.00,
    condition: "Excelente",
    status: "Ativo",
    createdAt: "2026-06-04T12:25:00Z",
  },
  {
    id: "lst_11",
    stickerId: "stk_17", // Maradona Divine
    sellerId: "usr_alice",
    sellerName: "Alice Trader",
    price: 650.00,
    condition: "Excelente",
    status: "Ativo",
    createdAt: "2026-06-04T12:30:00Z",
  }
];

export const GUEST_USERS = [
  {
    id: "usr_felipe",
    name: "Felipe (Colecionador)",
    email: "felipe@trocacard.com.br",
    walletBalance: 850.00,
    role: "user" as const,
    avatar: "🎒",
    joinedDate: "2025-02-15",
    initialCards: [
      { stickerId: "stk_1", qty: 1, condition: "Excelente" as const },
      { stickerId: "stk_3", qty: 2, condition: "Excelente" as const },
      { stickerId: "stk_7", qty: 1, condition: "Muito Bom" as const },
      { stickerId: "stk_10", qty: 3, condition: "Excelente" as const },
      { stickerId: "stk_12", qty: 2, condition: "Marcas de Uso" as const },
      { stickerId: "stk_16", qty: 1, condition: "Excelente" as const },
      { stickerId: "stk_13", qty: 1, condition: "Excelente" as const }
    ]
  },
  {
    id: "usr_mariana",
    name: "Mariana (StickerHunter)",
    email: "mariana@trocacard.com.br",
    walletBalance: 1200.00,
    role: "user" as const,
    avatar: "👒",
    joinedDate: "2025-05-20",
    initialCards: [
      { stickerId: "stk_2", qty: 1, condition: "Excelente" as const },
      { stickerId: "stk_5", qty: 1, condition: "Excelente" as const },
      { stickerId: "stk_4", qty: 2, condition: "Muito Bom" as const },
      { stickerId: "stk_8", qty: 4, condition: "Excelente" as const },
      { stickerId: "stk_14", qty: 1, condition: "Excelente" as const }
    ]
  },
  {
    id: "usr_vinicius",
    name: "Vinícius Admin",
    email: "vinicius@trocacard.com.br",
    walletBalance: 2500.00,
    role: "admin" as const,
    avatar: "👑",
    joinedDate: "2024-11-01",
    initialCards: [
      { stickerId: "stk_1", qty: 2, condition: "Excelente" as const },
      { stickerId: "stk_2", qty: 2, condition: "Excelente" as const },
      { stickerId: "stk_9", qty: 1, condition: "Excelente" as const },
      { stickerId: "stk_11", qty: 1, condition: "Excelente" as const },
      { stickerId: "stk_15", qty: 1, condition: "Excelente" as const }
    ]
  }
];

export const CATEGORIES = [
  "Todos",
  "Copa do Mundo",
  "Craques Atuais",
  "Lendas do Futebol",
  "Goleiros & Defensores",
  "Escudos & Logos"
];
